### ISSUE TITLE
Remote Images

### ISSUE THREAD

**Issue by NathanHazout** [sensorario/jitr#3]
It would be nice to use a remote URL as the source of the image.
Is it currently possible?

**Comment by sensorario** [comment]
I am working at new version 2.0. Are you already interested in this issue?

**Comment by NathanHazout** [comment]
It depends how far away is your 2.0

**Comment by sensorario** [comment]
At the moment works only with png files. I've just to fix this stuff and work on scaling of image. Maybe one or two days. I am just a bit unsettled: this is a totally rewritten extension: logic is completely different. Maybe I'll create a new one extension. I hate "justintimeresizer" as name.
